version: '3.5'
networks:
  backend-network:
    driver: bridge

services:
  back:
    build:
      context: ./
      dockerfile: ./back/Dockerfile
    environment:
      APP_PORT: 5000
    restart: always
    volumes:
    - ./back:/code
    ports:
    - 5000:5000
    networks:
     - backend-network

  front:
    build:
      context: ./
      dockerfile: ./front/Dockerfile
    stdin_open: true
    tty: true
    ports: 
        - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules